template_path: "transit-gateway-associations.j2"
stack_name: "TransitGatewayAssociation"
dependencies:
  - "prod/sage-tgw.yaml"
parameters:
  TgwRouteTableName: "sage-tgw"
sceptre_user_data:
  stackname: !stack_name
  tgw_attachment_ids:
    - "tgw-attach-00209ee1f8bf96deb"  # sandbox/sandcastlevpc
    - "tgw-attach-0eda99de834959854"  # itsandbox/dustbunnyvpc
    - "tgw-attach-07e89a05b741f9505"  # scicomp/computevpc
    - "tgw-attach-0c0095ff57f6f1662"  # scicomp/snowflakevpc
