template_path: "transit-gateway.j2"
stack_name: "sage-tgw"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/essentials.yaml"
  - "prod/unionstationvpc.yaml"
parameters:
  VpcRouteTableId: !stack_output_external unionstationvpc::PrivateRouteTable
  VpcId: !stack_output_external unionstationvpc::VPCId
  SubnetIds:
    - !stack_output_external unionstationvpc::PrivateSubnet
    - !stack_output_external unionstationvpc::PrivateSubnet1
    - !stack_output_external unionstationvpc::PrivateSubnet2
sceptre_user_data:
  TgwSpokes:
    dustbunnyvpc:
      AccountId: "804034162148"
      CIDR: "10.29.0.0/16"
    sandcastlevpc:
      AccountId: "563295687221"
      CIDR: "10.23.0.0/16"
