template_path: "transit-gateway.j2"
stack_name: "sage-tgw"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/unionstationvpc.yaml"
parameters:
  VpcId: !stack_output_external unionstationvpc::VPCId
  SubnetIds:
    - !stack_output_external unionstationvpc::PrivateSubnet
    - !stack_output_external unionstationvpc::PrivateSubnet1
    - !stack_output_external unionstationvpc::PrivateSubnet2
sceptre_user_data:
  TgwSpokes:
    dustbunnyvpc:
      AccountId: "804034162148"
    sandcastlevpc:
      AccountId: "563295687221"
